# Generated by Django 5.1 on 2024-12-04 08:10

from django.db import migrations


def migrate_author_to_contribution(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    for blog in Blog.objects.all():
        if blog.author:
            blog.contributors.add(blog.author, through_defaults={'contribution': 'Auteur Principal'})


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_alter_blog_author_blogcontributor_blog_contributors'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_contribution)
    ]
