# Generated by Django 5.1 on 2024-12-02 09:53

from django.db import migrations


def assign_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_blog = Permission.objects.get(codename='add_blog')
    change_blog = Permission.objects.get(codename='change_blog')
    delete_blog = Permission.objects.get(codename='delete_blog')
    view_blog = Permission.objects.get(codename='view_blog')

    creators_permission = [
        add_blog, change_blog, delete_blog, view_blog
    ]

    # creation des groupes et assigne des permissions en fonction de chacun
    creators = Group.objects.get(name='creators')
    creators.permissions.set(creators_permission)

    subscribers = Group.objects.get(name='subscriber')
    subscribers.permissions.add(view_blog)


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(assign_permissions)
    ]
